# Generated by Django 2.1.2 on 2018-10-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_delete_product_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='calorie',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
