# Generated by Django 2.1.2 on 2018-10-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_info_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('cal', models.IntegerField()),
            ],
        ),
    ]
