# Generated by Django 2.1.2 on 2018-10-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='item',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
    ]
